# nixpacks.toml  – Python + full-feature FFmpeg (tblend, lut3d, rubberband)

[phases.setup]
packages = [
  "ffmpeg",                      # minimal FFmpeg (overwritten later)
  "python3",
  "gcc",
  "software-properties-common",  # lets us add a PPA
  "curl",
  "ca-certificates"
]

[phases.install]
cmds = [
  # Install full-filter FFmpeg 6.x
  "add-apt-repository -y ppa:jonathonf/ffmpeg-6",
  "apt-get update -y",
  "apt-get install -y ffmpeg",
  # Python dependencies
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]
