# nixpacks.toml  – full-feature FFmpeg build + Python

###############################################################################
# 1. Base packages you wanted                                                 #
###############################################################################
[phases.setup]
packages = ["ffmpeg", "python3", "gcc", "curl", "ca-certificates"]

###############################################################################
# 2. Install phase – get full FFmpeg 6.x from PPA                             #
###############################################################################
[phases.install]
cmds = [
  # install software-properties-common so we get add-apt-repository
  "apt-get update -y && apt-get install -y software-properties-common",
  # add the PPA that ships ffmpeg with tblend, lut3d, rubberband, etc.
  "add-apt-repository -y ppa:jonathonf/ffmpeg-6",
  "apt-get update -y",
  "apt-get install -y ffmpeg",
  # python deps
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

###############################################################################
# 3. Procfile already starts `python app.py`, so no [start] block needed      #
###############################################################################
